apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data
  labels:
    app: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard