apiVersion: apps/v1
kind: Deployment
metadata:
  name: bennyfi-jobs-testnet
  namespace: bennyfi
  labels:
    app: bennyfi-jobs
    env: telos-testnet
spec:
  selector:
    matchLabels:
      app: bennyfi-jobs
      env: telos-testnet
  replicas: 1
  template:
    metadata:
      labels:
        app: bennyfi-jobs
        env: telos-testnet
    spec:
      containers:
      - name: bennyfi-jobs
        image: sebastianmontero/bennyfi-jobs:v0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: CONTRACT_NAME
            value: "bennyfitest4"
          - name: EOS_ENDPOINT
            value: "https://testnet.telos.caleos.io"
          - name: RUN_INTERVAL_MINS
            value: "2"
        envFrom:
          - secretRef:
             name: bennyfi-jobs-testnet