apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-mainnet-node-manager-nfs
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs