apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-daoctl-prometheus
  labels:
    app: daoctl-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-daoctl-prometheus
  labels:
    app: daoctl-prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-daoctl-prometheus
  labels:
    app: daoctl-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-daoctl-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-daoctl-prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: daoctl-daoctl-prometheus
  labels:
    app: daoctl-prometheus
    prometheus: daoctl-prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitor: alpha-daoctl-prometheus
  endpoints:
  - port: http-alpha
    path: /debug/prometheus_metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: daoctl-prometheus
  labels:
    app: daoctl-prometheus
spec:
  serviceAccountName: prometheus-daoctl-prometheus
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-daoctl-prometheus
      port: web
  serviceMonitorSelector:
    matchLabels:
      app: daoctl-prometheus
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      app: daoctl-prometheus
      prometheus: daoctl-prometheus
      role: alert-rules
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: daoctl-prometheus
  labels:
    app: daoctl-prometheus  
spec:
  type: NodePort
  selector:
    app: daoctl-prometheus
  ports:
    - name: hypha-prom
      protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daoctl-prometheus
  labels:
    app: daoctl-prometheus  
spec:
  selector:
    matchLabels:
      app: daoctl-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: daoctl-prometheus
    spec:
      containers:
        - name: daoctl-prometheus
          image: dsmaxds/daoctl:v0.3.10
          ports:
            - containerPort: 8085
          env:
          - name: DAOCTL_EOSIOENDPOINT
            value: "https://api.telos.kitchen"
