apiVersion: apps/v1
kind: Deployment
metadata:
  name: bennyfi-vrf-oracle-test
  namespace: bennyfi-test
  labels:
    app: vrf-oracle
    env: test
spec:
  selector:
    matchLabels:
      app: vrf-oracle
      env: test
  replicas: 1
  template:
    metadata:
      labels:
        app: vrf-oracle
        env: test
    spec:
      containers:
      - name: bennyfi-vrf-oracle-test
        image: sebastianmontero/vrf-oracle-test:10d8af5f41daf66efca954a36fc7368545814b1c
        imagePullPolicy: IfNotPresent
        #command: ["ls"]
        command: ["/usr/local/go/bin/go"]
        args: ["run", "./start-vrf-oracle.go"]
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        env:
          - name: EOS_URL
            value: "http://bennyfi-test-dfuse-service-cluster.bennyfi-test.svc.cluster.local:8888"
          - name: FIREHOSE_ENDPOINT
            value: "bennyfi-test-dfuse-service-cluster.bennyfi-test.svc.cluster.local:9000"
          - name: VRF_START_BLOCK_NUM
            value: "1"
          - name: VRF_CONTRACT
            value: "vrftesttest1"
          - name: VRF_JOB_TABLE
            value: "jobs"
          - name: VRF_HEART_BEAT_FREQUENCY
            value: "100"
        envFrom:
          - secretRef:
             name: bennyfi-vrf-test-secrets
