
# To increase volume size:
# 1. Set the storage value on this file to the desired value and apply changes.
# 2. Edit the each of the pvcs: kubectl patch pvc tikv-basic-tikv-1 -p '{"spec":{"resources":{"requests":{"storage":"900Gi"}}}}}'
# 3. Restart pods (delete each of the tikv pods)

apiVersion: tikv.org/v1alpha1
kind: TikvCluster
metadata:
  name: basic
spec:
  version: v4.0.10
  configUpdateStrategy: RollingUpdate
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  # schedulerName: tikv-scheduler
  pd:
    baseImage: pingcap/pd
    replicas: 3
    requests:
      storage: "50Gi"
    config:
      log:
        level: info
      replication:
        location-labels:
        - zone
        max-replicas: 3
    nodeSelector:
      dedicated: pd
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: pd
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    requests:
      storage: "900Gi"
    annotations:
      tidb.pingcap.com/sysctl-init: "true"
    # podSecurityContext:
    #   sysctls:
    #   - name: net.core.somaxconn
    #     value: "32768"
    config: {}
    nodeSelector:
      dedicated: tikv
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: tikv
