apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-router
  namespace: dfuse
  labels:
    app: dfuse-router
    env: telos-mainnet
data:
  router.yaml: |
    start:
      args:
      - search-router
      flags:
        log-to-file: false
        #log-format: stackdriver
        common-blockmeta-addr: telos-mainnet-blockmeta.dfuse.svc.cluster.local:13014
        search-common-mesh-dsn: etcd://etcd-cluster-client.dfuse.svc.cluster.local:2379/1
        search-common-mesh-service-version: v3
        search-router-enable-retry: false
        search-router-head-delay-tolerance: 3
        search-router-lib-delay-tolerance: 0
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-router
  namespace: dfuse
  labels:
    app: dfuse-router
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse-router
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-router
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:2807c7e
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/router.yaml", "-vv"]
        ports:
        - containerPort: 13018
          name: grpc
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-router
          mountPath: /config/router.yaml
          subPath: router.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-router
        configMap:
          name: telos-mainnet-router
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-router
  namespace: dfuse
  labels:
    app: dfuse-router
    env: telos-mainnet
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 13018
    targetPort: 13018
    protocol: TCP
  selector:
    app: dfuse-router
    env: telos-mainnet
