apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-eosq
  namespace: dfuse
  labels:
    app: dfuse-eosq
    env: telos-mainnet
data:
  eosq.yaml: |
    start:
      args:
      - eosq
      flags:
        log-to-file: false
        #log-format: stackdriver
        common-chain-core-symbol: "4,TLOS"
        eosq-api-endpoint-url: "https://dfuse.tekit.io"
        eosq-available-networks: "[{ \"id\": \"local\", \"is_test\": true, \"logo\": \"/images/eos-mainnet.png\", \"name\": \"Local Network\", \"url\": \"https://dfuse.tekit.io\" }]"
        eosq-default-network: local
        eosq-display-price: true
        eosq-price-ticker-name: TLOS
        eosq-environment: production
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-eosq
  namespace: dfuse
  labels:
    app: dfuse-eosq
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse-eosq
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-eosq
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/eosq.yaml", "-vvv"]
        ports:
        - containerPort: 13030
          name: http
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-eosq
          mountPath: /config/eosq.yaml
          subPath: eosq.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-eosq
        configMap:
          name: telos-mainnet-eosq
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-eosq
  namespace: dfuse
  labels:
    app: dfuse-eosq
    env: telos-mainnet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 13030
    targetPort: 13030
    protocol: TCP
  selector:
    app: dfuse-eosq
    env: telos-mainnet
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dfuse-telos-mainnet-eosq
  namespace: dfuse
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - deosq.tekit.io
    secretName: deosq-tekit-io
  rules:
  - host: deosq.tekit.io
    http:
      paths:
        - path: /
          backend:
            serviceName: dfuse-telos-mainnet-eosq
            servicePort: 13030