apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-node-manager-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60
    access-control-allow-origin = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = false
    contracts-console = true
    p2p-peer-address = testnet.telosusa.io:19877
    p2p-peer-address = node1.testnet2.telosglobal.io:9876
    p2p-peer-address = node2.testnet2.telosglobal.io:9876
    p2p-peer-address = basho-p2p.telosuk.io:19876
    p2p-peer-address = peer.tlostest.alohaeos.com:9876
    p2p-peer-address = nickfury.tlos.goodblock.io:9876
    p2p-peer-address = api.basho.eostribe.io:9880
    p2p-peer-address = telos-test.greymass.com:19871
    p2p-peer-address = testnet.telos.caleos.io:9880
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-node-manager-config
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  node-manager.yaml: |
    start:
      args:
      - node-manager
      flags:
        log-to-file: true
        common-exclude-filter-expr: (account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))) || (account == 'nebulatpstps' || receiver == 'nebulatpstps' || (account == 'eosio.token' && (data.to == 'nebulatpstps' || data.from == 'nebulatpstps'))) || (account == 'fullblasting' || receiver == 'fullblasting' || (account == 'eosio.token' && (data.to == 'fullblasting' || data.from == 'fullblasting')))
        node-manager-http-listen-addr: :8080
        node-manager-config-dir: /config
        node-manager-data-dir: /data
        node-manager-auto-snapshot-modulo: 10000000
        node-manager-snapshot-store-url: gs://telos-testnet/snapshots
        node-manager-restore-snapshot-name: 0092179388-057e8bbc651307a12f42d94f82fac0dc4a94e8f3b4ceb1d3298686631269a071-snapshot.bin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-testnet-node-manager-pvc
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-testnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  replicas: 1
  serviceName: node-manager-telos-testnet-svc 
  selector:
    matchLabels:
      app: dfuse
      env: telos-testnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-testnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-manager.yaml", "--data-dir", "/data", "-v"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: node-mgr
          protocol: TCP

        volumeMounts:
        - name: telos-testnet-node-manager-pvc
          mountPath: /data

        - name: telos-testnet-node-manager-config
          mountPath: /config/node-manager.yaml
          subPath: node-manager.yaml

        - name: dfuse-node-manager-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

      volumes:
      - name: telos-testnet-node-manager-pvc
        persistentVolumeClaim:
          claimName: telos-testnet-node-manager-pvc
    
      - name: telos-testnet-node-manager-config
        configMap:
          name: telos-testnet-node-manager-config

      - name: dfuse-node-manager-config-ini
        configMap:
          name: telos-testnet-node-manager-config-ini

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: node-manager-telos-testnet-svc
  namespace: dfuse
  labels:
    app: dfuse
    end: telos-testnet
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr
  selector:
    app: dfuse
    env: telos-testnet