apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-merger
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  merger.yaml: |
    start:
      args:
      - merger
      flags:
        log-to-file: true
        common-blocks-store-url: gs://telos-testnet/merged
        common-oneblock-store-url: gs://telos-testnet/one
        merger-start-block-num: 90959299
        merger-minimal-block-num: 90959299
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-testnet-merger
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse
      env: telos-testnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-testnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/merger.yaml","-v"]
        volumeMounts:
        - name: telos-testnet-merger
          mountPath: /config/merger.yaml
          subPath: merger.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-testnet-merger
        configMap:
          name: telos-testnet-merger
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420