apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-mainnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  replicas: 1
  serviceName: telos-mainnet-node-manager
  selector:
    matchLabels:
      app: dfuse
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-manager.yaml", "--data-dir", "/data", "-vv"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: node-mgr
          protocol: TCP
        - containerPort: 9876
          name: p2p
          protocol: TCP

        volumeMounts:
        - name: telos-mainnet-node-manager-data
          mountPath: /data

        - name: telos-mainnet-node-manager-config
          mountPath: /config/node-manager.yaml
          subPath: node-manager.yaml

        - name: telos-mainnet-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

      volumes:
      - name: telos-mainnet-node-manager-data
        persistentVolumeClaim:
          claimName: telos-mainnet-node-manager-data
    
      - name: telos-mainnet-node-manager-config
        configMap:
          name: telos-mainnet-node-manager-config

      - name: telos-mainnet-config-ini
        configMap:
          name: telos-mainnet-config-ini

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420