apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-mainnet-node-manager-pvc
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-node-manager-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    chain-state-db-size-mb = 65536
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60
    access-control-allow-origin = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = false
    contracts-console = true
    p2p-peer-address = p2p.telos.zenblocks.io:9876
    p2p-peer-address = peer.telos.alohaeos.com:9876
    p2p-peer-address = mainnet.telosusa.io:9877
    p2p-peer-address = p2p.telos.eosdetroit.io:1337
    p2p-peer-address = p2p.telos.cryptosuvi.io:2222
    p2p-peer-address = api.telos.eostribe.io:7876
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
data:
  node-manager.yaml: |
    start:
      args:
      - node-manager
      flags:
        log-to-file: true
        common-exclude-filter-expr: (account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))) || (account == 'nebulatpstps' || receiver == 'nebulatpstps' || (account == 'eosio.token' && (data.to == 'nebulatpstps' || data.from == 'nebulatpstps'))) || (account == 'fullblasting' || receiver == 'fullblasting' || (account == 'eosio.token' && (data.to == 'fullblasting' || data.from == 'fullblasting')))
        node-manager-http-listen-addr: :8080
        node-manager-config-dir: /config
        node-manager-data-dir: /data
        node-manager-auto-snapshot-period: 48h
        node-manager-snapshot-store-url: gs://telos-mainnet/snapshots
        node-manager-restore-snapshot-name: 0093249004-058eddec2c519b1934ea58beb53a5dfeabe21cb04b7d241f339ab0ee80fbcde3-snapshot.bin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  replicas: 1
  # serviceName: node-manager-telos-mainnet-svc
  selector:
    matchLabels:
      app: dfuse
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-manager.yaml", "--data-dir", "/data", "-vv"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: node-mgr
          protocol: TCP

        volumeMounts:
        - name: telos-mainnet-node-manager-pvc
          mountPath: /data

        - name: telos-mainnet-node-manager
          mountPath: /config/node-manager.yaml
          subPath: node-manager.yaml

        - name: telos-mainnet-node-manager-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

      volumes:
      - name: telos-mainnet-node-manager-pvc
        persistentVolumeClaim:
          claimName: telos-mainnet-node-manager-pvc
    
      - name: telos-mainnet-node-manager
        configMap:
          name: telos-mainnet-node-manager

      - name: telos-mainnet-node-manager-config-ini
        configMap:
          name: telos-mainnet-node-manager-config-ini

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: node-manager-telos-mainnet-svc
  namespace: dfuse
  labels:
    app: dfuse
    end: telos-mainnet
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr
  selector:
    app: dfuse
    env: telos-mainnet