---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bennyfi-test-api-nodeos-config-ini
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
data:
  config.ini: |
    plugin = eosio::http_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin

    contracts-console = true
    enable-account-queries = true

    abi-serializer-max-time-ms = 30000

    # HTTP
    access-control-allow-origin = *
    http-server-address = 0.0.0.0:8888
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true

    # P2P
    agent-name = dfuse producer node
    p2p-server-address = 0.0.0.0:9877
    p2p-listen-endpoint = 0.0.0.0:9877
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60

    p2p-peer-address=bennyfi-test-node-mgr-cluster.bennyfi-test.svc.cluster.local:9877

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bennyfi-test-api-node-mgr-config
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
data:
  node-mgr.yaml: |
    start:
      args:
      - node-manager
      flags:
        log-to-file: false
        node-manager-config-dir: /config/producer
        node-manager-http-listen-addr: ":13008"
        node-manager-nodeos-api-addr: ":8888"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bennyfi-test-api-node-mgr
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bennyfi-test-api-node-mgr
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
spec:
  replicas: 1
  serviceName: bennyfi-test-dfuse-service
  selector:
    matchLabels:
      app: bennyfi-test-api-node-mgr
      env: local
  template:
    metadata:
      namespace: bennyfi-test
      labels:
        app: bennyfi-test-api-node-mgr
        env: local
    spec:
      # serviceAccountName: dfuse-service-account
      # serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-mgr.yaml", "--data-dir", "/dfuse-data", "-vv"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 9877
          name: p2p
          protocol: TCP
        volumeMounts:
        - name: bennyfi-test-api-node-mgr
          mountPath: /dfuse-data
        - name: bennyfi-test-api-node-mgr-config
          mountPath: /config/node-mgr.yaml
          subPath: node-mgr.yaml
        - name: bennyfi-test-api-nodeos-config-ini
          mountPath: /config/producer/config.ini
          subPath: config.ini
        - name: bennyfi-nodeos-test-genesis
          mountPath: /config/producer/genesis.json
          subPath: genesis.json
        # - name: dfuse-service-account-token-jsp6h
        #   readOnly: true
        #   mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: bennyfi-test-api-node-mgr
        persistentVolumeClaim:
          claimName: bennyfi-test-api-node-mgr
      - name: bennyfi-test-api-node-mgr-config
        configMap:
          name: bennyfi-test-api-node-mgr-config
      - name: bennyfi-test-api-nodeos-config-ini
        configMap:
          name: bennyfi-test-api-nodeos-config-ini
      - name: bennyfi-nodeos-test-genesis
        configMap:
          name: bennyfi-test-genesis
      # - name: dfuse-service-account-token-jsp6h
      #   secret:
      #     secretName: dfuse-service-account-token-jsp6h
      #     defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: bennyfi-test-api-node-mgr
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 32088
    protocol: TCP
    name: nodeos-api
  selector:
    app: bennyfi-test-api-node-mgr
    env: local

---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
  name: bennyfi-test-api-node-mgr-cluster
  namespace: bennyfi-test
  labels:
    app: bennyfi-test-api-node-mgr
    env: local
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 9877
    targetPort: 9877
    protocol: TCP
    name: p2p
  selector:
    app: bennyfi-test-api-node-mgr
    env: local