apiVersion: v1
kind: ConfigMap
metadata:
  name: bennyfi-test-mindreader-config-ini
  namespace: bennyfi-test
  labels:
    app: dfuse-bennyfi-test
    env: local
data:
  config.ini: |
    # Plugins
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin

    ## Required for state snapshots API call to work
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin

    # Chain
    chain-state-db-size-mb = 8192
    reversible-blocks-db-size-mb = 340
    max-transaction-time = 5000

    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false

    # P2P
    agent-name = dfuse for EOSIO (mindreader)
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60

    # HTTP
    access-control-allow-origin = *
    http-server-address = 0.0.0.0:8889
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true

    # EOS VM is not supported on OS X platform, you **should** enable if you are running on Unix, it speeds up tremendously reprocessing
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4

    # Enable deep mind
    deep-mind = true
    contracts-console = true

    ## Peers
    p2p-peer-address=bennyfi-test-node-mgr-cluster.bennyfi-test.svc.cluster.local:9877

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bennyfi-test-dfuse-config
  namespace: bennyfi-test
  labels:
    app: dfuse-bennyfi-test
    env: local
data:
  dfuse.yaml: |
    start:
      args:
      - merger
      - mindreader
      - blockmeta
      - relayer
      - firehose
      flags:
        log-to-file: false
        common-blocks-store-url: /dfuse-data/blocks/merged
        common-oneblock-store-url: /dfuse-data/blocks/one
        mindreader-manager-api-addr: :8080
        mindreader-nodeos-api-addr: localhost:8889
        mindreader-config-dir: /config/mindreader
        mindreader-snapshot-store-url: /dfuse-data/snapshots
        mindreader-merge-threshold-block-age: 2h
        mindreader-blocks-chan-capacity: 100000
        mindreader-start-failure-handler: false
        mindreader-log-to-zap: true
        mindreader-shutdown-delay: 20s
        merger-max-one-block-operations-batch-size: 50000
        firehose-grpc-listen-addr: ":9000*"
        blockmeta-eos-api-upstream-addr: :8889
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bennyfi-test-dfuse-data
  namespace: bennyfi-test
  labels:
    app: dfuse-bennyfi-test
    env: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bennyfi-test-dfuse-statefulset
  namespace: bennyfi-test
  labels:
    app: dfuse-bennyfi-test
    env: local
spec:
  replicas: 1
  serviceName: bennyfi-test-dfuse-service
  selector:
    matchLabels:
      app: dfuse-bennyfi-test
      env: local
  template:
    metadata:
      namespace: bennyfi-test
      labels:
        app: dfuse-bennyfi-test
        env: local
    spec:
      # serviceAccountName: dfuse-service-account
      # serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/dfuse.yaml", "--data-dir", "/dfuse-data", "-vv"]
        ports:
        - containerPort: 9000
          name: firehose
          protocol: TCP
        volumeMounts:
        - name: bennyfi-test-dfuse-data
          mountPath: /dfuse-data
        - name: bennyfi-test-dfuse-config
          mountPath: /config/dfuse.yaml
          subPath: dfuse.yaml
        - name: bennyfi-test-mindreader-config-ini
          mountPath: /config/mindreader/config.ini
          subPath: config.ini
        - name: bennyfi-mindreader-test-genesis
          mountPath: /config/mindreader/genesis.json
          subPath: genesis.json
        # - name: dfuse-service-account-token-jsp6h
        #   readOnly: true
        #   mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: bennyfi-test-dfuse-data
        persistentVolumeClaim:
          claimName: bennyfi-test-dfuse-data
      - name: bennyfi-test-dfuse-config
        configMap:
          name: bennyfi-test-dfuse-config
      - name: bennyfi-test-mindreader-config-ini
        configMap:
          name: bennyfi-test-mindreader-config-ini
      - name: bennyfi-mindreader-test-genesis
        configMap:
          name: bennyfi-test-genesis
      # - name: dfuse-service-account-token-jsp6h
      #   secret:
      #     secretName: dfuse-service-account-token-jsp6h
      #     defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
  name: bennyfi-test-dfuse-service-cluster
  namespace: bennyfi-test
  labels:
    app: dfuse-bennyfi-test
    env: local
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: firehose
  selector:
    app: dfuse-bennyfi-test
    env: local