apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-mindreader-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    chain-state-db-size-mb = 65536
    max-transaction-time = 5000
    read-mode = head
    #p2p-accept-transactions = true
    #api-accept-transactions = true
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    http-server-address = 0.0.0.0:8888
    p2p-max-nodes-per-host = 100
    connection-cleanup-period = 60
    access-control-allow-origin = *
    access-control-allow-headers = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit    
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    reversible-blocks-db-size-mb = 4096
    p2p-peer-address = api.telos.kitchen:9876
    p2p-peer-address = peer.telos.alohaeos.com:9876
    p2p-peer-address = mainnet.telosusa.io:9877
    p2p-peer-address = p2p.telos.eosdetroit.io:1337
    p2p-peer-address = p2p.telos.cryptosuvi.io:2222
    p2p-peer-address = api.telos.eostribe.io:7876
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-primary-config
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet-primary
data:
  dfuse-config.yaml: |
    start:
      args:
      - eosws
      - dgraphql
      - mindreader
      - blockmeta
      - apiproxy
      - abicodec
      #- eosq
      - dashboard
      - trxdb-loader
      - search-archive
      - search-indexer
      #- search-live
      - search-router
      - relayer
      - statedb
      flags:
        common-include-filter-expr: account == 'dao.hypha' || receiver == 'dao.hypha' || account == 'bank.hypha' || receiver == 'bank.hypha' || account == 'token.hypha' || receiver == 'token.hypha' || account == 'msig.hypha' || receiver == 'msig.hypha' || account == 'eosio.msig' || account == 'kv.hypha' || account == 'voice.hypha' || account == 'husd.hypha' || account == 'token.seeds' || account == 'escrow.seeds' || receiver == 'escrow.seeds'
        common-trxdb-dsn: tikv://basic-pd.default:2379/trxdb
        common-blocks-store-url: gs://telos-mainnet/merged
        common-oneblock-store-url: gs://telos-mainnet/one 
        eosq-available-networks: '[{ "id": "hypha", "is_test": false, "logo": "https://dho.hypha.earth/app-logo-128x128.png", "name": "Hypha", "url": "https://eosq.tekit.io" }]'
        eosq-default-network: hypha
        statedb-store-dsn: tikv://basic-pd.default:2379/statedb
        node-manager-http-listen-addr: :8080
        node-manager-config-dir: /config
        node-manager-data-dir: /data
        node-manager-auto-snapshot-modulo: 5000000
        node-manager-snapshot-store-url: gs://telos-mainnet/snapshots
        node-manager-restore-snapshot-name: 0139384734-084ed79ef566945fce6ffe1be7d03b9d175ae316f69723b55d0e6a8910a23c4b-snapshot.bin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-mainnet-primary-data
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet-primary
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-mainnet-primary
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet-primary
spec:
  serviceName: dfuse-mainnet-primary
  replicas: 1
  selector:
    matchLabels:
      app: dfuse
      env: telos-mainnet-primary
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-mainnet-primary
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:latest
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/dfuse-config.yaml", "-vv"]
        ports:
        - containerPort: 8081
          name: dash
          protocol: TCP

        - containerPort: 8080
          name: api-mgr
          protocol: TCP

        - containerPort: 8888
          protocol: TCP
          name: nodeos-api

        - containerPort: 8999
          protocol: TCP
          name: node-mgr
        
        - containerPort: 13031
          protocol: TCP
          name: dash-grpc

        - containerPort: 13008
          protocol: TCP
          name: dash-nmgr

        - containerPort: 13010
          protocol: TCP
          name: mind-grpc

        - containerPort: 13011
          protocol: TCP
          name: relayer

        - containerPort: 9102
          protocol: TCP
          name: prom
        
        - containerPort: 13013
          protocol: TCP
          name: abi

        - containerPort: 13018
          protocol: TCP
          name: abi-search
        
        - containerPort: 13023
          protocol: TCP
          name: dgql
        
        - containerPort: 13024
          protocol: TCP
          name: dgql-grpc
        
        - containerPort: 13026
          protocol: TCP
          name: eosws        

        - containerPort: 13014
          protocol: TCP
          name: blockmeta

        - containerPort: 13030
          protocol: TCP
          name: eosq
                       
        volumeMounts:
        - name: telos-mainnet-primary-config
          mountPath: /config/dfuse-config.yaml
          subPath: dfuse-config.yaml

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

        - name: telos-mainnet-mindreader-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: telos-mainnet-primary-data
          mountPath: /data

      volumes:

      - name: telos-mainnet-primary-data
        persistentVolumeClaim:
          claimName: telos-mainnet-primary-data

      - name: telos-mainnet-primary-config
        configMap:
          name: telos-mainnet-primary-config
      
      - name: telos-mainnet-mindreader-config-ini
        configMap:
          name: telos-mainnet-mindreader-config-ini

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-mainnet-primary
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet-primary
spec:
  selector:
    app: dfuse
    env: telos-mainnet-primary

  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api

  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr

  - port: 8081
    targetPort: 8081
    name: dash
    protocol: TCP

  - port: 8999
    targetPort: 8999
    name: node-mgr
    protocol: TCP

  - targetPort: 13031
    port: 13031
    protocol: TCP
    name: dash-grpc

  - targetPort: 13008
    port: 13008
    protocol: TCP
    name: dash-nmgr

  - targetPort: 13010
    port: 13010
    protocol: TCP
    name: mind-grpc

  - targetPort: 13011
    port: 13011
    protocol: TCP
    name: relayer

  - targetPort: 9102
    port: 9102
    protocol: TCP
    name: prom
  
  - targetPort: 13013
    port: 13013
    protocol: TCP
    name: abi

  - targetPort: 13018
    port: 13018
    protocol: TCP
    name: abi-search
  
  - targetPort: 13023
    port: 13023
    protocol: TCP
    name: dgql
  
  - targetPort: 13024
    port: 13024
    protocol: TCP
    name: dgql-grpc
  
  - targetPort: 13026
    port: 13026
    protocol: TCP
    name: eosws        

  - targetPort: 13014
    port: 13014
    protocol: TCP
    name: blockmeta

  - targetPort: 13030
    port: 13030
    protocol: TCP
    name: eosq
---
