apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-forkresolver
  namespace: dfuse
  labels:
    app: dfuse-forkresolver
    env: telos-mainnet
data:
  forkresolver.yaml: |
    start:
      args:
      - search-forkresolver
      flags:
        log-to-file: false
        #log-format: stackdriver
        common-blocks-store-url: gs://telos-mainnet/merged
        search-common-mesh-dsn: etcd://etcd-cluster-client.dfuse.svc.cluster.local:2379/1
        search-common-mesh-service-version: v3
        search-common-mesh-publish-interval: 1s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-forkresolver
  namespace: dfuse
  labels:
    app: dfuse-forkresolver
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse-forkresolver
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-forkresolver
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/forkresolver.yaml", "-vv"]
        ports:
        - containerPort: 13027
          name: grpc
          protocol: TCP
        - containerPort: 13028
          name: http
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-forkresolver
          mountPath: /config/forkresolver.yaml
          subPath: forkresolver.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-forkresolver
        configMap:
          name: telos-mainnet-forkresolver
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-forkresolver
  namespace: dfuse
  labels:
    app: dfuse-forkresolver
    env: telos-mainnet
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 13027
    targetPort: 13027    
    protocol: TCP
  - name: http
    port: 13028
    targetPort: 13028
    protocol: TCP
  selector:
    app: dfuse-forkresolver
    env: telos-mainnet
