apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-archive-50000
  namespace: dfuse
  labels:
    app: dfuse-archive-50000
    env: telos-mainnet
data:
  archive.yaml: |
    start:
      args:
      - search-archive
      flags:
        log-to-file: true
        search-common-indices-store-url: gs://telos-mainnet/indices
        search-archive-indices-dl-threads: 20
        search-archive-tier-level: 50000
        search-archive-writable-path: /dfuse-data/search/archiver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-mainnet-archive-50000-pvc
  namespace: dfuse
  labels:
    app: dfuse-archive-50000
    env: telos-mainnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-mainnet-archive-50000
  namespace: dfuse
  labels:
    app: dfuse-archive-50000
    env: telos-mainnet
spec:
  replicas: 1
  serviceName: telos-mainnet-archive-50000
  selector:
    matchLabels:
      app: dfuse-archive-50000
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-archive-50000
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/archive.yaml","-v"]
        ports:
          - containerPort: 13015
            name: grpc
          - containerPort: 13016
            name: http
        volumeMounts:
        - name: telos-mainnet-archive-50000-pvc
          mountPath: /dfuse-data
        - name: telos-mainnet-archive-50000
          mountPath: /config/archive.yaml
          subPath: archive.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-archive-50000-pvc
        persistentVolumeClaim:
          claimName: telos-mainnet-archive-50000-pvc
      - name: telos-mainnet-archive-50000
        configMap:
          name: telos-mainnet-archive-50000
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-archive-50000
  namespace: dfuse
  labels:
    app: dfuse-archive-50000
    env: telos-mainnet
spec:
  ports:
  - port: 13015
    targetPort: 13015
    protocol: TCP
    name: grpc
  - port: 13016
    targetPort: 13016
    protocol: TCP
    name: http