apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-dgraphql
  namespace: dfuse
  labels:
    app: dfuse-dgraphql
    env: telos-mainnet
data:
  dgraphql.yaml: |
    start:
      args:
      - dgraphql
      flags:
        log-to-file: false
        #log-format: stackdriver
        common-blockmeta-addr: telos-mainnet-blockmeta.dfuse.svc.cluster.local:13014
        common-search-addr: dfuse-telos-mainnet-router.dfuse.svc.cluster.local:13018
        common-system-shutdown-signal-delay: 30s
        common-trxdb-dsn: tikv://basic-pd.default.svc:2379/trxdb?prefix=namespace_prefix
        dgraphql-disable-authentication: true
        dgraphql-override-trace-id: false
        dgraphql-protocol: EOS
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-dgraphql
  namespace: dfuse
  labels:
    app: dfuse-dgraphql
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse-dgraphql
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-dgraphql
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:2807c7e
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/dgraphql.yaml", "-vvvv"]
        ports:
        - containerPort: 13023
          name: http
          protocol: TCP
        - containerPort: 13024
          name: grpc
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-dgraphql
          mountPath: /config/dgraphql.yaml
          subPath: dgraphql.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-dgraphql
        configMap:
          name: telos-mainnet-dgraphql
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-dgraphql
  namespace: dfuse
  labels:
    app: dfuse-dgraphql
    env: telos-mainnet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 13023
    targetPort: 13023
    protocol: TCP
  - name: grpc
    port: 13024
    targetPort: 13024
    protocol: TCP
  selector:
    app: dfuse-dgraphql
    env: telos-mainnet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dfuse-telos-mainnet-dgraphql
  namespace: dfuse
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dgql.tekit.io
    secretName: dgql-tekit-io
  rules:
  - host: dgql.tekit.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dfuse-telos-mainnet-dgraphql
            port:
              number: 13023