apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    chain-state-db-size-mb = 8192
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen-dfuse-mindreader
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60
    access-control-allow-origin = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    p2p-peer-address=testnet2.telos.eosusa.news:59877
    p2p-peer-address=node1.testnet2.telosglobal.io:9876
    p2p-peer-address=node2.testnet2.telosglobal.io:9876
    p2p-peer-address=basho.eos.barcelona:9899
    p2p-peer-address=sslapi.teloscentral.com:9875
    p2p-peer-address=145.239.133.188:5566
    p2p-peer-address=testnet.telos.eclipse24.io:6789
    p2p-peer-address=testnet2.telos.eosdetroit.io:1337
    p2p-peer-address=basho-p2p.telosuk.io:19876
    p2p-peer-address=telos-testnet.atticlab.net:7876
    p2p-peer-address=testnet.eossweden.eu:8022
    p2p-peer-address=testnet.telos.cryptosuvi.io:2223
    p2p-peer-address=nickfury.tlos.goodblock.io:9876
    p2p-peer-address=telosapi.eosmetal.io:59877
    p2p-peer-address=207.148.6.75:9877
    p2p-peer-address=p2p.testnet2.telosgermany.io
    p2p-peer-address=176.9.86.214:9877
    p2p-peer-address=telos-testnet-b.eosphere.io:9825
    p2p-peer-address=testnet.telos.africa:9875
    p2p-peer-address=p2p.testnet.telosgreen.com:9876
    p2p-peer-address=testnet2p2p.telosarabia.net:9876
    p2p-peer-address=157.230.29.117:9876
    p2p-peer-address=test.telos.kitchen:9876
    p2p-peer-address=prod.testnet.bp.teleology.world:9876
    p2p-peer-address=telos-testnet.eoscafeblock.com:9879
    p2p-peer-address=p2p.basho.telos.dutcheos.io:7654
    p2p-peer-address=testnet-b.telos-21zephyr.com:9876
    p2p-peer-address=p2p.testnet.telosunlimited.io:9876
    p2p-peer-address=peer.tlostest.alohaeos.com:9876
    p2p-peer-address=52.175.222.202:9877
    p2p-peer-address=testnet2.telos.eosindex.io:9876
    p2p-peer-address=basho.sofos.network:9876
    p2p-peer-address=85.152.18.129:39876
    p2p-peer-address=telostestnet.ikuwara.com:9876
    p2p-peer-address=p2p.testnet.nytelos.com:8012
    p2p-peer-address=telos.basho.eosdublin.io:9876
    p2p-peer-address=telos-testnet.cryptolions.io:9871
    p2p-peer-address=api.basho.eostribe.io:9880
    p2p-peer-address=p2p-telos-testnet.hkeos.com:59876
---