apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-mindreader
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  mindreader.yaml: |
    start:
      args:
      - mindreader
      flags:
        log-to-file: true
        common-blocks-store-url: /data/mindreader/blocks/merged
        common-oneblock-store-url: /data/mindreader/blocks/one
        common-exclude-filter-expr: account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))
        mindreader-manager-api-addr: :8080
        mindreader-nodeos-api-addr: localhost:8888
        mindreader-config-dir: /config
        mindreader-readiness-max-latency: 5s
        mindreader-snapshot-store-url: ./snapshots
        mindreader-blocks-chan-capacity: 100000
        mindreader-start-failure-handler: false
        mindreader-log-to-zap: true
        mindreader-shutdown-delay: 20s
        mindreader-start-block-num: 1
---
        

