apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-eosws
  namespace: dfuse
  labels:
    app: dfuse-eosws
    env: telos-mainnet
data:
  eosws.yaml: |
    start:
      args:
      - eosws
      flags:
        log-to-file: false
        #log-format: stackdriver
        common-blockmeta-addr: telos-mainnet-blockmeta.dfuse.svc.cluster.local:13014
        common-blocks-store-url: gs://telos-mainnet/merged
        common-blockstream-addr: telos-mainnet-relayer.dfuse.svc.cluster.local:13011
        common-chain-core-symbol: "4,TLOS"
        common-search-addr: dfuse-telos-mainnet-router.dfuse.svc.cluster.local:13018
        common-system-shutdown-signal-delay: 30s
        common-trxdb-dsn: tikv://basic-pd.default.svc:2379/trxdb?prefix=namespace_prefix
        eosws-nodeos-rpc-addr: telos.caleos.io:443
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-mainnet-eosws
  namespace: dfuse
  labels:
    app: dfuse-eosws
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse-eosws
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-eosws
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:80117b5
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/eosws.yaml", "-vvv"]
        ports:
        - containerPort: 13026
          name: http
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-eosws
          mountPath: /config/eosws.yaml
          subPath: eosws.yaml
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-eosws
        configMap:
          name: telos-mainnet-eosws
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-eosws
  namespace: dfuse
  labels:
    app: dfuse-eosws
    env: telos-mainnet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 13026
    targetPort: 13026
    protocol: TCP
  selector:
    app: dfuse-eosws
    env: telos-mainnet