apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dfuse-blocks-telos-mainnet
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfuse-telos-mainnet-mindreader
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/mindreader.yaml", "--data-dir", "/data", "-v"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: mindrdr-mgr
          protocol: TCP

        volumeMounts:
        - name: dfuse-blocks-telos-mainnet
          mountPath: /data

        - name: dfuse-mindreader-config
          mountPath: /config/mindreader.yaml
          subPath: mindreader.yaml

        - name: dfuse-mindreader-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-mindreader-genesis-json
          mountPath: /config/genesis.json
          subPath: genesis.json

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

      # nodeSelector:
      #   env: telos-mainnet

      volumes:
      - name: dfuse-blocks-telos-mainnet
        persistentVolumeClaim:
          claimName: dfuse-blocks-telos-mainnet

      - name: dfuse-mindreader-config
        configMap:
          name: telos-mainnet-mindreader

      - name: dfuse-mindreader-config-ini
        configMap:
          name: telos-mainnet-mindreader-config-ini

      - name: dfuse-mindreader-genesis-json
        configMap:
          name: telos-mainnet-genesis-json

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: dfuse-telos-mainnet-mindreader
  namespace: dfuse
  labels:
    app: dfuse
    end: telos-mainnet
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr
  selector:
    app: dfuse
    env: telos-mainnet