apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-mindreader-nodeos-config-v2
  namespace: dfuse
  labels:
    app: dfuse-mindreader-mindreader
    env: telos-mainnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    chain-state-db-size-mb = 65536
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    http-server-address = 0.0.0.0:8888
    p2p-max-nodes-per-host = 100
    connection-cleanup-period = 60
    access-control-allow-origin = *
    access-control-allow-headers = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit    
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    reversible-blocks-db-size-mb = 4096
    p2p-peer-address = p2p.telos-21zephyr.com:9876
    p2p-peer-address = seed.telosmadrid.io:9876
    p2p-peer-address = p2p.telosunlimited.io:9876
    p2p-peer-address = p2p.tlos.goodblock.io:9877
    p2p-peer-address = p2p.telosuk.io:9876
    p2p-peer-address = p2p.theteloscope.io:9876
    p2p-peer-address = api.eosimpera:9876
    p2p-peer-address = telos.caleos.io:9880 
    p2p-peer-address = p2p.telos.cryptosuvi.io:2222
    p2p-peer-address = p2p.kainosbp.com:9876
    p2p-peer-address = telos.eu.eosamsterdam.net:9120
    p2p-peer-address = telos.greymass.com:19871
    p2p-peer-address = node1.us-west.telosglobal.io:9876
    p2p-peer-address = api.telos.kitchen:9876
    p2p-peer-address = seed.teloskorea.com:9876
    p2p-peer-address = seed-bridge.teloskorea.com:9876
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-mindreader-dfuse-config-v2
  namespace: dfuse
  labels:
    app: dfuse-mindreader
    env: telos-mainnet
data:
  mindreader.yaml: |
    start:
      args:
      - mindreader
      flags:
        log-to-file: false
        common-blocks-store-url: gs://telos-mainnet/merged
        common-oneblock-store-url: gs://telos-mainnet/one-v2
        common-exclude-filter-expr: (account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))) || (account == 'nebulatpstps' || receiver == 'nebulatpstps' || (account == 'eosio.token' && (data.to == 'nebulatpstps' || data.from == 'nebulatpstps'))) || (account == 'fullblasting' || receiver == 'fullblasting' || (account == 'eosio.token' && (data.to == 'fullblasting' || data.from == 'fullblasting')))
        mindreader-manager-api-addr: :8080
        mindreader-nodeos-api-addr: localhost:8888
        mindreader-connection-watchdog: false
        mindreader-config-dir: /config
        mindreader-readiness-max-latency: 5s
        mindreader-blocks-chan-capacity: 100000
        mindreader-start-failure-handler: false
        mindreader-log-to-zap: true
        mindreader-shutdown-delay: 20s
        mindreader-snapshot-store-url: gs://telos-mainnet/snapshots
        #mindreader-restore-snapshot-name: 0141993833-0876a769cc800a5701e85c4bdac239a38a496f91d09028d53a1134f5ed732ffb-snapshot.bin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-mainnet-mindreader-statefulset-v2
  namespace: dfuse
  labels:
    app: dfuse-mindreader
    env: telos-mainnet
spec:
  replicas: 1
  serviceName: telos-mainnet-mindreader-headless-v2
  selector:
    matchLabels:
      app: dfuse-mindreader
      env: telos-mainnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse-mindreader
        env: telos-mainnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:2807c7e
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/mindreader.yaml", "--data-dir", "/data", "-vv"]
        ports:
        - containerPort: 13010
          name: grpc
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: mindrdr-mgr
          protocol: TCP
        - containerPort: 9000
          name: mon1
          protocol: TCP
        - containerPort: 9102
          name: mon2
          protocol: TCP
        volumeMounts:
        - name: telos-mainnet-mindreader-pvc-v2
          mountPath: /data
        - name: telos-mainnet-mindreader-dfuse-config-v2
          mountPath: /config/mindreader.yaml
          subPath: mindreader.yaml
        - name: telos-mainnet-mindreader-nodeos-config-v2
          mountPath: /config/config.ini
          subPath: config.ini
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: telos-mainnet-mindreader-dfuse-config-v2
        configMap:
          name: telos-mainnet-mindreader-dfuse-config-v2
      - name: telos-mainnet-mindreader-nodeos-config-v2
        configMap:
          name: telos-mainnet-mindreader-nodeos-config-v2
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
  volumeClaimTemplates:
  - metadata:
      name: telos-mainnet-mindreader-pvc-v2
      namespace: dfuse
      labels:
        app: dfuse-mindreader
        env: telos-mainnet
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
  name: telos-mainnet-mindreader-headless-v2
  namespace: dfuse
  labels:
    app: dfuse-mindreader
    env: telos-mainnet
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 13010
    targetPort: 13010    
    protocol: TCP
  - name: nodeos-api
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: dfuse-mindreader
    env: telos-mainnet