apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-mainnet-mindreader-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-mainnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    chain-state-db-size-mb = 65536
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    http-server-address = 0.0.0.0:8888
    p2p-max-nodes-per-host = 100
    connection-cleanup-period = 60
    access-control-allow-origin = *
    access-control-allow-headers = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit    
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    reversible-blocks-db-size-mb = 4096
    p2p-peer-address = p2p.telos-21zephyr.com:9876
    p2p-peer-address = seed.telosmadrid.io:9876
    p2p-peer-address = p2p.telosunlimited.io:9876
    p2p-peer-address = p2p.tlos.goodblock.io:9877
    p2p-peer-address = p2p.telosuk.io:9876
    p2p-peer-address = p2p.theteloscope.io:9876
    p2p-peer-address = api.eosimpera:9876
    p2p-peer-address = telos.caleos.io:9880 
    p2p-peer-address = p2p.telos.cryptosuvi.io:2222
    p2p-peer-address = p2p.kainosbp.com:9876
    p2p-peer-address = telos.eu.eosamsterdam.net:9120
    p2p-peer-address = telos.greymass.com:19871
    p2p-peer-address = node1.us-west.telosglobal.io:9876
    p2p-peer-address = api.telos.kitchen:9876
    p2p-peer-address = seed.teloskorea.com:9876
    p2p-peer-address = seed-bridge.teloskorea.com:9876