apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-mindreader-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = false
    api-accept-transactions = false
    agent-name = telos-kitchen-dfuse-mindreader
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    p2p-max-nodes-per-host = 2
    connection-cleanup-period = 60
    access-control-allow-origin = *
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    p2p-peer-address = testnet.telosusa.io:19877
    p2p-peer-address = node1.testnet2.telosglobal.io:9876
    p2p-peer-address = node2.testnet2.telosglobal.io:9876
    p2p-peer-address = basho-p2p.telosuk.io:19876
    p2p-peer-address = peer.tlostest.alohaeos.com:9876
    p2p-peer-address = nickfury.tlos.goodblock.io:9876
    p2p-peer-address = api.basho.eostribe.io:9880
    p2p-peer-address = telos-test.greymass.com:19871
    p2p-peer-address = testnet.telos.caleos.io:9880
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-genesis-json
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  genesis.json: |
    {
      "initial_timestamp": "2019-08-07T12:00:00.000",
      "initial_key": "EOS7xyPWfh6743fhZ46zQQcXSctddoqG65d44YsyRnCJCs54mJLrH",
      "initial_configuration": {
        "max_block_net_usage": 1048576,
        "target_block_net_usage_pct": 1000,
        "max_transaction_net_usage": 524288,
        "base_per_transaction_net_usage": 12,
        "net_usage_leeway": 500,
        "context_free_discount_net_usage_num": 20,
        "context_free_discount_net_usage_den": 100,
        "max_block_cpu_usage": 5000000,
        "target_block_cpu_usage_pct": 1000,
        "max_transaction_cpu_usage": 150000,
        "min_transaction_cpu_usage": 100,
        "max_transaction_lifetime": 3600,
        "deferred_trx_expiration_window": 600,
        "max_transaction_delay": 3888000,
        "max_inline_action_size": 4096,
        "max_inline_action_depth": 4,
        "max_authority_depth": 6
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-mindreader
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  mindreader.yaml: |
    start:
      args:
      - mindreader
      flags:
        log-to-file: true
        common-blocks-store-url: gs://telos-testnet/merged
        common-oneblock-store-url: gs://telos-testnet/one
        common-exclude-filter-expr: (account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))) || (account == 'nebulatpstps' || receiver == 'nebulatpstps' || (account == 'eosio.token' && (data.to == 'nebulatpstps' || data.from == 'nebulatpstps'))) || (account == 'fullblasting' || receiver == 'fullblasting' || (account == 'eosio.token' && (data.to == 'fullblasting' || data.from == 'fullblasting')))
        mindreader-manager-api-addr: :8080
        mindreader-nodeos-api-addr: localhost:8888
        mindreader-config-dir: /config
        mindreader-readiness-max-latency: 5s
        mindreader-blocks-chan-capacity: 100000
        mindreader-start-failure-handler: false
        mindreader-log-to-zap: true
        mindreader-shutdown-delay: 20s
        mindreader-batch-mode: true
        mindreader-start-block-num: 0
        mindreader-stop-block-num: 9999
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindreader-telos-testnet-from-genesis
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: dfuse-pod-testnet
#   namespace: dfuse
#   labels:
#     app: dfuse
#     env: telos-testnet
#     sa: dfuse-service-account
# spec:
#   volumes:
#     - name: dfuse-service-account-token-jsp6h
#       secret:
#         secretName: dfuse-service-account-token-jsp6h
#         defaultMode: 420
#   containers:
#   - image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
#     command:
#       - "sleep"
#       - "1204800"
#     imagePullPolicy: IfNotPresent
#     volumeMounts:
#       - name: dfuse-service-account-token-jsp6h
#         readOnly: true
#         mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#     name: cloud-sdk
#   serviceAccountName: dfuse-service-account
#   serviceAccount: dfuse-service-account
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mindreader-telos-testnet-from-genesis
  namespace: dfuse
  labels:
      app: dfuse
      env: telos-testnet
      sa: dfuse-service-account
spec:
  replicas: 1
  serviceName: mindreader-telos-testnet-from-genesis
  selector:
    matchLabels:
      app: dfuse
      env: telos-testnet
      sa: dfuse-service-account
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-testnet
        sa: dfuse-service-account
    spec:
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/mindreader.yaml", "--data-dir", "/data", "-v"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: mindrdr-mgr
          protocol: TCP
        volumeMounts:
        - name: mindreader-telos-testnet-from-genesis
          mountPath: /data
        - name: telos-testnet-mindreader
          mountPath: /config/mindreader.yaml
          subPath: mindreader.yaml
        - name: dfuse-mindreader-config-ini-testnet
          mountPath: /config/config.ini
          subPath: config.ini
        - name: telos-testnet-genesis-json
          mountPath: /config/genesis.json
          subPath: genesis.json
        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: mindreader-telos-testnet-from-genesis
        persistentVolumeClaim:
          claimName: mindreader-telos-testnet-from-genesis
      - name: telos-testnet-mindreader
        configMap:
          name: telos-testnet-mindreader
      - name: dfuse-mindreader-config-ini-testnet
        configMap:
          name: telos-testnet-mindreader-config-ini
      - name: telos-testnet-genesis-json
        configMap:
          name: telos-testnet-genesis-json
      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: mindreader-telos-testnet-from-genesis
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
    sa: dfuse-service-account
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr
  selector:
    app: dfuse
    env: telos-testnet
    sa: dfuse-service-account