apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-testnet-node-manager-pvc
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telos-testnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfuse
      env: telos-testnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-testnet
    spec:
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio
        imagePullPolicy: IfNotPresent
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-manager.yaml", "--data-dir", "/data", "-vvv"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: node-mgr
          protocol: TCP

        volumeMounts:
        - name: telos-testnet-node-manager-pvc
          mountPath: /data

        - name: telos-testnet-node-manager-config
          mountPath: /config/node-manager.yaml
          subPath: node-manager.yaml

        - name: dfuse-node-manager-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-node-manager-genesis-json
          mountPath: /config/genesis.json
          subPath: genesis.json

      nodeSelector:
        env: telos-testnet
        
      volumes:
      - name: telos-testnet-node-manager-pvc
        persistentVolumeClaim:
          claimName: telos-testnet-node-manager-pvc
    
      - name: telos-testnet-node-manager-config
        configMap:
          name: telos-testnet-node-manager-config

      - name: dfuse-node-manager-config-ini
        configMap:
          name: telos-testnet-node-manager-config-ini

      - name: dfuse-node-manager-genesis-json
        configMap:
          name: telos-testnet-genesis-json