apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-config-ini
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  config.ini: |
    plugin = eosio::chain_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::db_size_api_plugin
    plugin = eosio::net_api_plugin
    plugin = eosio::producer_plugin
    plugin = eosio::producer_api_plugin
    max-transaction-time = 5000
    read-mode = head
    p2p-accept-transactions = true
    api-accept-transactions = true
    agent-name = telos-kitchen
    p2p-server-address = 127.0.0.1:9876
    p2p-listen-endpoint = 127.0.0.1:9876
    http-server-address = 0.0.0.0:8888
    p2p-max-nodes-per-host = 100
    connection-cleanup-period = 60
    http-max-response-time-ms = 1000
    http-validate-host = false
    verbose-http-errors = true
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true
    eos-vm-oc-compile-threads = 4
    deep-mind = true
    contracts-console = true
    access-control-allow-origin = *
    access-control-allow-headers = *
    #chain-state-db-size-mb = 65536
    reversible-blocks-db-size-mb = 4096
    p2p-peer-address = test.telos.kitchen:9876
    p2p-peer-address = testnet.telosusa.io:19877
    p2p-peer-address = basho-p2p.telosuk.io:19876
    p2p-peer-address = peer.tlostest.alohaeos.com:9876
    p2p-peer-address = nickfury.tlos.goodblock.io:9876
    p2p-peer-address = api.basho.eostribe.io:9880
    p2p-peer-address = testnet.telos.caleos.io:9880
    p2p-peer-address=testnet2.telos.eosusa.news:59877
    p2p-peer-address=basho.eos.barcelona:9899
    p2p-peer-address=testnet.telos.eclipse24.io:6789
    p2p-peer-address=testnet2.telos.eosdetroit.io:1337
    p2p-peer-address=telos-testnet.atticlab.net:7876
    p2p-peer-address=testnet.eossweden.eu:8022
    p2p-peer-address=telosapi.eosmetal.io:59877
    p2p-peer-address=testnet2p2p.telosarabia.net:9876
    p2p-peer-address=157.230.29.117:9876
    p2p-peer-address=prod.testnet.bp.teleology.world:9876
    p2p-peer-address=testnet-b.telos-21zephyr.com:9876
    p2p-peer-address=p2p.testnet.telosunlimited.io:9876
    p2p-peer-address=basho.sofos.network:9876
    p2p-peer-address=telos-testnet.cryptolions.io:9871
    p2p-peer-address=api.basho.eostribe.io:9880
    p2p-peer-address=p2p-telos-testnet.hkeos.com:59876
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telos-testnet-node-manager-config
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
data:
  node-manager.yaml: |
    start:
      args:
      - node-manager
      flags:
        log-to-file: true
        common-blocks-store-url: gs://telos-testnet/merged
        common-oneblock-store-url: gs://telos-testnet/one
        common-exclude-filter-expr: (account == 'richrichcoin' || receiver == 'richrichcoin' || (account == 'eosio.token' && (data.to == 'richrichcoin' || data.from == 'richrichcoin'))) || (account == 'nebulatpstps' || receiver == 'nebulatpstps' || (account == 'eosio.token' && (data.to == 'nebulatpstps' || data.from == 'nebulatpstps'))) || (account == 'fullblasting' || receiver == 'fullblasting' || (account == 'eosio.token' && (data.to == 'fullblasting' || data.from == 'fullblasting')))
        node-manager-http-listen-addr: :8080
        node-manager-config-dir: /config
        node-manager-data-dir: /data
        node-manager-auto-snapshot-modulo: 5000000
        node-manager-snapshot-store-url: gs://telos-testnet/snapshots
        #node-manager-restore-snapshot-name: 0093995954-059a43b23d6161e2ce66d602fa1d6850699e5c449db128d7cdb455e7f71224e2-snapshot.bin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telos-testnet-node-manager-data
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telos-testnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  replicas: 1
  serviceName: telos-testnet-node-manager
  selector:
    matchLabels:
      app: dfuse
      env: telos-testnet
  template:
    metadata:
      namespace: dfuse
      labels:
        app: dfuse
        env: telos-testnet
    spec:
      serviceAccountName: dfuse-service-account
      serviceAccount: dfuse/dfuse-service-account
      containers:
      - name: dfuse-eosio
        image: dfuse/dfuse-eosio:latest
        command: ["/app/dfuseeos"]
        args: ["start", "-c", "/config/node-manager.yaml", "--data-dir", "/data", "-vv"]
        ports:
        - containerPort: 8888
          name: nodeos-api
          protocol: TCP
        - containerPort: 8080
          name: node-mgr
          protocol: TCP
        - containerPort: 9876
          name: p2p
          protocol: TCP

        volumeMounts:
        - name: telos-testnet-node-manager-data
          mountPath: /data

        - name: telos-testnet-node-manager-config
          mountPath: /config/node-manager.yaml
          subPath: node-manager.yaml

        - name: telos-testnet-config-ini
          mountPath: /config/config.ini
          subPath: config.ini

        - name: dfuse-service-account-token-jsp6h
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

      volumes:
      - name: telos-testnet-node-manager-data
        persistentVolumeClaim:
          claimName: telos-testnet-node-manager-data
    
      - name: telos-testnet-node-manager-config
        configMap:
          name: telos-testnet-node-manager-config

      - name: telos-testnet-config-ini
        configMap:
          name: telos-testnet-config-ini

      - name: dfuse-service-account-token-jsp6h
        secret:
          secretName: dfuse-service-account-token-jsp6h
          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: telos-testnet-node-manager
  namespace: dfuse
  labels:
    app: dfuse
    env: telos-testnet
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: nodeos-api
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: mindrdr-mgr
  - port: 9876
    targetPort: 9876
    protocol: TCP
    name: p2p
  selector:
    app: dfuse
    env: telos-testnet
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: telos-testnet-node-manager-p2p
#   namespace: dfuse
#   labels:
#     app: dfuse
#     end: telos-testnet
# spec:
#   type: NodePort
#   ports:

#   selector:
#     app: dfuse
#     env: telos-testnet