apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dfuse-telos-mainnet-proxy
  namespace: dfuse
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - dfuse.tekit.io
    secretName: dfuse-tekit-io
  rules:
  - host: dfuse.tekit.io
    http:
      paths:
      - path: /dfuse.eosio.v1.GraphQL/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-dgraphql
          servicePort: 13024
      - path: /dfuse.graphql.v1.GraphQL/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-dgraphql
          servicePort: 13024
      - path: /grpc.reflection.v1alpha.ServerReflection/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-dgraphql
          servicePort: 13024
      # - path: /graphiql
      #   pathType: Prefix
      #   backend:
      #     serviceName: dfuse-telos-mainnet-dgraphql
      #     servicePort: 13023
      - path: /graphiql/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-dgraphql
          servicePort: 13023
      - path: /graphql
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-dgraphql
          servicePort: 13023
      - path: /v1/chain/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-eosws
          servicePort: 13026
      - path: /v1/stream
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-eosws
          servicePort: 13026
      - path: /v0/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-eosws
          servicePort: 13026
      - path: /v1/
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-eosws
          servicePort: 13026
      - path: /
        pathType: Prefix
        backend:
          serviceName: dfuse-telos-mainnet-eosws
          servicePort: 13026